### ISSUE TITLE
Feature Request: Dynamic  model to select 

### ISSUE THREAD

**Issue by dedguy21** [anki-code/xontrib-openai#2]
Hi! Thank you for the awesome xontrib! I gave it a star!

I've found that ... The current hard coded model (which is currently the best to select) is hard coded. I'm on the wait list for GPT four, and and have already used it through the website. When it becomes available I would have to go into the xontrib and hard coded the gpt-4 selection, and if it's limited, when I need to go back to text-dacinci or even choose gpt3.5-turbo model, I would have to go back to xontrib and adjust the code. 

I'm wondering How hard would it be to write the code so that at least the three major models were part of a drop down selection? 

Anyways this is all just a suggestion. The text-davinci model does everything one could currently ask. 

I've already starred the repo. 

Thanks 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
You can change the model by setting `$OPENAI_MODEL` env variable:
```xsh
xontrib load openai
aliases['ai4'] = "$OPENAI_MODEL='gpt-4' @('ai')"

ai! i want to ask default model

ai4! i want to ask gpt 4 model
```
It will be cool for you to read [xonsh-cheatsheet](https://github.com/anki-code/xonsh-cheatsheet/blob/main/README.md)

**Comment by anki-code** [comment]
JFYI if you want to use the output:

```xsh
import json
j = json.loads($(ai give me small json))
j
# {'name': 'John', 'age': 25}
```
